workflows:
  ios-build:
    name: iOS Build
    instance_type: mac_mini_m2
    max_build_duration: 60
    environment:
      flutter: 3.27.4
      xcode: 16.1
    scripts:
      - name: 清理 Flutter 构建缓存
        script: flutter clean
      - name: 获取 Dart 依赖
        script: flutter pub get
      - name: 更新 CocoaPods 源
        script: pod repo update
      - name: 构建 iOS
        script: flutter build ios --release
    artifacts:
      - build/ios/ipa/*.ipa

  my-workflow:
    name: TOIM
    labels:
      - QA
      - ${{ TENANT_NAME || 'default-tenant' }}  # 使用默认值避免出现 none
    instance_type: mac_mini_m2
    max_build_duration: 60
    inputs:
      name:
        description: Input description
        default: Codemagic
    environment:
      groups:
        - group_name
      vars:
        PUBLIC_ENV_VAR: "value here"
        TENANT_NAME: "your-tenant-name"  # 明确定义变量
      flutter: stable
      xcode: latest
    cache:
      cache_paths:
        - ~/.pub-cache
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: '*'
          include: true
          source: true
      cancel_previous_builds: false
    scripts:
      - echo "Hello, ${{ inputs.name }}"
      - flutter clean
      - flutter pub get
      - flutter build appbundle --release
    artifacts:
      - build/**/outputs/bundle/**/*.aab
    publishing:
      email:
        recipients:
          - name@example.com
      scripts:
        - echo 'Post-publish script'