workflows:
  ios-build:
    name: iOS Build
    instance_type: mac_mini_m2
    max_build_duration: 60
    environment:
      flutter: 3.27.4
      xcode: 16.1
      vars:
        TENANT_NAME: "default-tenant"
        # 1. 定义 Shell 可识别的环境变量（无需 ${{ }} 包裹）
        IOS_BUNDLE_ID: "io.openim.flutter.demoo"
        IOS_NOTIFICATION_BUNDLE_ID: "io.openim.flutter.demoo.NotificationService"
        IOS_SIGNING_CERT_P12: ${{ IOS_SIGNING_CERT_P12 }}
        IOS_SIGNING_CERT_PASSWORD: ${{ IOS_SIGNING_CERT_PASSWORD }}
        IOS_MAIN_PROFILE: ${{ IOS_MAIN_PROFILE }}
        IOS_NOTIFICATION_PROFILE: ${{ IOS_NOTIFICATION_PROFILE }}
        IOS_MAIN_PROFILE_NAME: ${{ IOS_MAIN_PROFILE_NAME }}
        IOS_NOTIFICATION_PROFILE_NAME: ${{ IOS_NOTIFICATION_PROFILE_NAME }}
    scripts:
      - name: 清理 Flutter 缓存
        script: flutter clean

      - name: 获取 Dart 依赖
        script: flutter pub get

      - name: 准备 iOS 依赖
        script: |
          cd ios
          rm -rf Podfile.lock Pods ~/Library/Caches/CocoaPods
          pod repo update
          pod install --repo-update
          cd ..

      - name: 导入 iOS 签名证书和配置文件
        script: |
          # 使用 Shell 变量格式 $变量名
          echo "$IOS_SIGNING_CERT_P12" | base64 --decode > signing_cert.p12
          security create-keychain -p "" build.keychain
          security default-keychain -s build.keychain
          security unlock-keychain -p "" build.keychain
          security import signing_cert.p12 -k build.keychain -P "$IOS_SIGNING_CERT_PASSWORD" -T /usr/bin/codesign -T /Applications/Xcode-16.1.app/Contents/Developer/usr/bin/xcodebuild
          security set-key-partition-list -S apple-tool:,apple: -k "" build.keychain

          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles/
          echo "$IOS_MAIN_PROFILE" | base64 --decode > ~/Library/MobileDevice/Provisioning\ Profiles/main_profile.mobileprovision
          echo "$IOS_NOTIFICATION_PROFILE" | base64 --decode > ~/Library/MobileDevice/Provisioning\ Profiles/notification_profile.mobileprovision

      - name: 生成 ExportOptions.plist（修复变量语法）
        script: |
          # 2. 关键修复：用 $变量名 替代 ${{ 变量名 }}，Shell 可正常解析
          cat > ios/ExportOptions.plist << EOF
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
            <key>method</key>
            <string>ad-hoc</string>
            <key>provisioningProfiles</key>
            <dict>
              <key>$IOS_BUNDLE_ID</key>
              <string>$IOS_MAIN_PROFILE_NAME</string>
              <key>$IOS_NOTIFICATION_BUNDLE_ID</key>
              <string>$IOS_NOTIFICATION_PROFILE_NAME</string>
            </dict>
            <key>signingCertificate</key>
            <string>iPhone Distribution</string>
            <key>signingStyle</key>
            <string>manual</string>
            <key>stripSwiftSymbols</key>
            <true/>
            <key>uploadBitcode</key>
            <false/>
            <key>uploadSymbols</key>
            <true/>
          </dict>
          </plist>
          EOF

      - name: 构建并归档 iOS 应用
        script: |
          flutter build ios --release --no-codesign --bundle-suffix ""
          cd ios
          xcodebuild archive \
            -workspace Runner.xcworkspace \
            -scheme Runner \
            -configuration Release \
            -archivePath ../build/ios/archive/Runner.xcarchive \
            -allowProvisioningUpdates \
            CODE_SIGN_KEYCHAIN=~/build.keychain \
            CODE_SIGN_IDENTITY="iPhone Distribution" \
            PROVISIONING_PROFILE_SPECIFIER="$IOS_MAIN_PROFILE_NAME"  # 用 Shell 变量格式
          xcodebuild -exportArchive \
            -archivePath ../build/ios/archive/Runner.xcarchive \
            -exportPath ../build/ios/ipa \
            -exportOptionsPlist ExportOptions.plist
          cd ..

    artifacts:
      - build/ios/ipa/*.ipa
      - build/ios/archive/*.xcarchive

  my-workflow:
    name: TOIM
    labels:
      - QA
      - ${{ TENANT_NAME }}
    instance_type: mac_mini_m2
    max_build_duration: 60
    inputs:
      name:
        description: 输入名称
        default: Codemagic
    environment:
      groups:
        - group_name
      vars:
        PUBLIC_ENV_VAR: "value here"
        TENANT_NAME: "default-tenant"
      flutter: stable
      xcode: latest
    cache:
      cache_paths:
        - ~/.pub-cache
        - ios/Pods
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: "*"
          include: true
          source: true
      cancel_previous_builds: false
    scripts:
      - echo "Hello, ${{ inputs.name }}"
      - flutter clean
      - flutter pub get
      - cd ios && pod repo update && pod install --repo-update && cd ..
      - flutter build appbundle --release
    artifacts:
      - build/**/outputs/bundle/**/*.aab
    publishing:
      email:
        recipients:
          - name@example.com
      scripts:
        - echo "发布后脚本执行"